.circleci/config.yml

chore: circleci project setup

---

.babelrc
.circleci/config.yml
aw.config.js
babel.config.js
package.json
src/table/__tests__/utils.spec.js
yarn.lock

chore: init unit tests

---

src/table/cells/selections.jsx

fixes #34
This will most likely change when UX have a say about things, but this looks more or less as the old table

feat: proper selection styling

---

src/index.js
src/mui-setup.js
src/table/table.jsx

fix: mui conflicts and overflow update

---

src/__test__/event-listeners.spec.js
src/event-listeners.js
src/index.js

fix: do not confirm selections when dragging scroll bar

---

src/index.js
src/table/TableHeadWrapper.jsx
src/table/__tests__/TableHeadWrapper.spec.jsx
src/table/__tests__/styling-utils.spec.js
src/table/styling-utils.js

Initial structure for header styling, similar work needs to be done for the table body

feat: header styling

---

rollup.config.js
src/index.js

The table wasn't properly returning the render promise due to how the load data is setup. Adding a promuse hook fixes this.

fix: properly wait for rendering

---

src/table/TableBodyWrapper.jsx
src/table/TableHeadWrapper.jsx
src/table/__tests__/TableBodyWrapper.spec.jsx
src/table/cells/__tests__/handle-key-press.spec.js
src/table/cells/handle-key-press.js

When focusing on a header cell, pressing enter or space should update the sorting #128

feat: change sorting by pressing enter or space 

---

src/index.js
src/table/TableBodyWrapper.jsx
src/table/__tests__/TableBodyWrapper.spec.jsx
src/table/cells/withColumnStyling.jsx
src/table/cells/withSelections.jsx

fix: update styling when theme changes

---

src/mui-setup.js

fix: set color to inherit on tableSortLabel

---

src/table/TableBodyWrapper.jsx

fix: the values for a measure are empty when added

---

package.json
src/table/TableHeadWrapper.jsx
src/table/__tests__/TableHeadWrapper.spec.jsx

when cells are selected or in edit mode, it should not be able to do the sorting

disable sorting in selection

---

.codeclimate.yml
api-specifications/properties.json
src/__test__/ext.spec.js
src/ext.js
src/object-properties.js

fixes #175 
All the new components in `ext.js` are from the straight table, so all the translation strings are correct etc

feat: adding properties to pp and documentation to object-properties

---

src/table/Root.jsx

a tool for highlighting potential problems in an application.
https://reactjs.org/docs/strict-mode.html

chore: add StrictMode

---

src/mui-setup.js
src/table/TableBodyWrapper.jsx
src/table/TableWrapper.jsx

feature: make fixed header look good

---

src/table/TableWrapper.jsx
src/table/__tests__/TableWrapper.spec.jsx

fix: rows per page drop down is inaccessible

---

src/table/TableBodyWrapper.jsx

fix: add th to first column

---

locale/locales/de.json
locale/locales/es.json
locale/locales/fr.json
locale/locales/it.json
locale/locales/ja.json
locale/locales/ko.json
locale/locales/nl.json
locale/locales/pl.json
locale/locales/pt.json
locale/locales/ru.json
locale/locales/sv.json
locale/locales/tr.json
locale/locales/zh-CN.json
locale/locales/zh-TW.json

feat(translations): UI bus - 2021-10-01
- Update translations related to: 985f638 - feat(locale): add localization (#263)
- Update translations related to: d3dd750 - feat(translation): all possible to be translated strings (#281)

feat(translations): UI bus - 2021-10-01

---

src/index.js
src/table/TableWrapper.jsx
src/table/__tests__/TableWrapper.spec.jsx
yarn.lock

useRect replaces  window.addEventListener('resize', resizeCallback);

fix: bottom toolbar in table should be responsive

---

locale/locales/de.json
locale/locales/es.json
locale/locales/fr.json
locale/locales/it.json
locale/locales/ja.json
locale/locales/ko.json
locale/locales/nl.json
locale/locales/pl.json
locale/locales/pt.json
locale/locales/ru.json
locale/locales/sv.json
locale/locales/tr.json
locale/locales/zh-CN.json
locale/locales/zh-TW.json

fix(translations): bugfixes - RDL-5173 - Bug Fix
Fixes:
* [RDL-5173](https://jira.qlikdev.com/browse/RDL-5173)

fix(translations): bugfixes - RDL-5173 - Bug Fix

---

api-specifications/properties.json

run `yarn spec` syncing the API specifications info version

chore: bump api-specifications info version

---

locale/locales/de.json
locale/locales/es.json
locale/locales/fr.json
locale/locales/it.json
locale/locales/ja.json
locale/locales/ko.json
locale/locales/nl.json
locale/locales/pl.json
locale/locales/pt.json
locale/locales/ru.json
locale/locales/sv.json
locale/locales/tr.json
locale/locales/zh-CN.json
locale/locales/zh-TW.json

feat(translations): UI bus - 2021-11-02
- Update translations related to: da5aa75 - fix: add translation string and fix styling

feat(translations): UI bus - 2021-11-02

---

tools/build.js

--mode string ("production"|"development")
"production" is the default value

chore: to have not minified bundle in the development mode

---

src/table/components/TableWrapper.jsx
src/table/utils/__tests__/handle-scroll.spec.js
src/table/utils/handle-scroll.js

need to consider scroll horizontally in right-to-left direction as well

fix: unable to scroll horizontally in right-to-left direction

---

src/locale/locales/de.json
src/locale/locales/es.json
src/locale/locales/fr.json
src/locale/locales/it.json
src/locale/locales/ja.json
src/locale/locales/ko.json
src/locale/locales/nl.json
src/locale/locales/pl.json
src/locale/locales/pt.json
src/locale/locales/ru.json
src/locale/locales/sv.json
src/locale/locales/tr.json
src/locale/locales/zh-CN.json
src/locale/locales/zh-TW.json

chore(translations): UI bus - 2022-02-04
- Update translations related to: bbfed28 - refactor: support right-to-left direction using styled-components as style engine (#434)

chore(translations): UI bus - 2022-02-04

---

src/handle-data.js
src/locale/src/index.js
src/table/components/TableBodyWrapper.jsx
src/table/components/TableHeadWrapper.jsx
src/table/components/__tests__/TableHeadWrapper.spec.jsx
src/table/components/withSelections.jsx
src/table/utils/__tests__/handle-key-press.spec.js
src/table/utils/__tests__/selections-util.spec.js
src/table/utils/__tests__/styling-utils.spec.js
src/table/utils/handle-accessibility.js
src/table/utils/selections-utils.js
src/table/utils/styling-utils.js

tableBackgroundColor->themeBackgroundColor
we->you
columnStyle.background->columnStyle.backgroundColor

refactor: rename and add comments

---

src/index.js
src/table/components/TableWrapper.jsx

For use in Analytics view where pagination is combined with extra content
Example Image:

feat: Add option to render pagination content inside specified element.

---

README.md

<script src="https://unpkg.com/@nebula.js/sn-table"></script>

docs(readme): load the sn-table through the script tag from unpkg

---

src/table/Root.jsx

https://reactjs.org/docs/react-dom.html#unmountcomponentatnode

fix: remove a mounted React component from the DOM

---

src/table/components/PaginationContent.jsx

fix: received false for a non-boolean attribute title

---

src/locale/locales/de.json
src/locale/locales/es.json
src/locale/locales/fr.json
src/locale/locales/it.json
src/locale/locales/ja.json
src/locale/locales/ko.json
src/locale/locales/nl.json
src/locale/locales/pl.json
src/locale/locales/pt.json
src/locale/locales/ru.json
src/locale/locales/sv.json
src/locale/locales/tr.json
src/locale/locales/zh-CN.json
src/locale/locales/zh-TW.json

chore(translations): UI bus - 2022-05-27
- Update translations related to: a1347f9 - refactor: format code and remove console log (#538)

chore(translations): UI bus - 2022-05-27

---

src/locale/locales/zh-CN.json

chore(translations): bugfixes - remove extra colon
Fixes:
* [RDL-5589](https://jira.qlikdev.com/browse/RDL-5589)

chore(translations): bugfixes - remove extra colon

---

src/__test__/handle-data.spec.js
src/handle-data.js
src/table/components/TableBodyWrapper.jsx
src/table/components/__tests__/withSelections.spec.jsx
src/table/components/withSelections.jsx
src/table/utils/__tests__/handle-key-press.spec.js
src/table/utils/handle-key-press.js

- check qLock in each qDimensionInfo
- when a cell is locked or not a dimension, the selection should not work

feat:  when a dimension is locked, disable selections on that dimension

---

src/table/Root.jsx

This also solves the selection toolbar not disappearing!

fix: remove strict mode

---

mashup-example/using-build-tool/qlik-sense-desktop/configure.js
mashup-example/without-build-tool/qlik-sense-desktop/index.js
src/table/components/TableBodyWrapper.jsx

constraints: {
active: true - turn off interactions that affect the state of the visual representation including selection, zoom, scroll, etc.
select: true - turn off selections.
passive: true - turn off interactions like tooltips.
},

docs: update comments for constraints to make it cleaer

---

package.json
yarn.lock

either bump @babel/preset-env or @babel/preset-react can cause the ci issue

chore: downgrade dependency

---

src/table/components/TableBodyWrapper.jsx
src/table/utils/__tests__/selections-util.spec.js
src/table/utils/handle-key-press.js
src/table/utils/selections-utils.js

since #570 was fixed in nebula, no need for these sanity checks anymore

fix: remove sanity check for selections API

---

src/__test__/handle-data.spec.js
src/handle-data.js

there is no label when there is no dimension in the first column

fix: total label should appear only on dimension with zero column order

---

src/table/utils/__tests__/color-utils.spec.ts
src/table/utils/color-utils.ts

fix: type error

---

src/nebula-hooks/use-sorting.ts
src/table/hooks/use-scroll-listener.ts
src/table/utils/color-utils.ts

Read more: https://kate-dev.medium.com/when-to-use-typescript-optional-property-how-is-it-different-from-declaring-property-as-undefined-2319a0ee1f07

fix: optional to undefined for parameter

---

src/handle-data.ts
src/table/components/__tests__/withSelections.spec.tsx
src/table/components/withSelections.tsx
src/table/constants.ts
src/table/types.ts
src/table/utils/__tests__/handle-key-press.spec.ts
src/table/utils/__tests__/selections-utils.spec.ts
src/table/utils/__tests__/styling-utils.spec.ts
src/table/utils/accessibility-utils.ts
src/table/utils/handle-key-press.ts
src/table/utils/selections-utils.ts
src/table/utils/styling-utils.ts

- move enums and other constant to constants.ts
- move selection types to types file to avoid circular deps
- create `KeyCodes` enum for key codes
- add more values to `StylingDefaults`

refactor: keep constants in seperate file

---

mashup-example/using-build-tool/qlik-sense-desktop/package.json
mashup-example/using-build-tool/qlik-sense-desktop/yarn.lock
mashup-example/using-build-tool/qlik-sense-enterprise-on-windows/package.json
mashup-example/using-build-tool/qlik-sense-enterprise-on-windows/yarn.lock
mashup-example/using-build-tool/qlik-sense-saas/package.json
mashup-example/using-build-tool/qlik-sense-saas/yarn.lock
package.json
yarn.lock

Since there are multiple auto-generated PRs for this, It was tricky to verify. Just combined them to make sure it builds and works as before

chore: use nebula 3.x everywhere

---

.github/CONTRIBUTION.md
README.md

moving up the contribution section in README so you wont miss it. Also some clarification around releasing

docs: clearify contribution

---

api-specifications/properties.json
src/__test__/ext.spec.js
src/ext.js
src/qae/object-properties.d.ts
src/qae/object-properties.js

Please make sure to go through the list below before adding reviewers.
If some checks aren't done, you can create a draft PR until they are.
Add support for chart exploration toggler
Other PRs connected to this:
- https://github.com/qlik-trial/sense-client/pull/21808 
- https://github.com/qlik-trial/analytics/pull/277

feat: chart-exploration-toggler

---

src/ext.js

Removed subtitle from sn-table definition

Removed subtitle from sn-table definition

---

src/table/components/CellText.tsx
src/table/components/TableBodyWrapper.tsx
src/table/components/TableHeadWrapper.tsx
src/table/components/TableTotals.tsx
src/table/utils/__tests__/copy-utils.spec.ts
src/table/utils/__tests__/handle-key-press.spec.ts
src/table/utils/copy-utils.ts

copyCell value can be copied properly on head cells via contextMenu

fix: copyCellValue on head cell when context menu is used

---

src/table/utils/__tests__/handle-click.spec.ts
src/table/utils/handle-click.ts

with flag off it was possible to make selections with right click

fix: only make selections on left click

---

src/ext/property-panel/__test__/data.spec.js
src/ext/property-panel/data.js

Change data section definition.

feat: change data section definition

---

package.json
yarn.lock

Updates the Nebula dependency and enables the systemJS build artifact.

chore: enable system js build

---

src/locale/locales/de.json
src/locale/locales/es.json
src/locale/locales/fr.json
src/locale/locales/it.json
src/locale/locales/ja.json
src/locale/locales/ko.json
src/locale/locales/nl.json
src/locale/locales/pl.json
src/locale/locales/pt.json
src/locale/locales/ru.json
src/locale/locales/sv.json
src/locale/locales/tr.json
src/locale/locales/zh-CN.json
src/locale/locales/zh-TW.json

chore(translations): UI bus - 2022-11-18
- Update translations related to: 2087c21 - Add a drop down menu to snTable header (#735)

chore(translations): UI bus - 2022-11-18

---

src/table/components/virtualized-table/Body.tsx
src/table/components/virtualized-table/TableContainer.tsx
src/table/components/virtualized-table/Wrapper.tsx
src/table/components/virtualized-table/__tests__/TableContainer.spec.tsx
src/table/components/virtualized-table/__tests__/Wrapper.spec.tsx
src/table/components/virtualized-table/hooks/use-infinite-scroll-data.ts
src/table/components/virtualized-table/hooks/use-on-props-change.ts

Fixes an issue where the virt table would call engine with a negative qTop value when fetching data.

fix: to large data fetch in virtualized table

---

src/index.ts
src/table/components/virtualized-table/TableContainer.tsx
src/table/components/virtualized-table/Wrapper.tsx
src/table/components/virtualized-table/__tests__/TableContainer.spec.tsx
src/table/components/virtualized-table/__tests__/Wrapper.spec.tsx
src/table/components/virtualized-table/hooks/__tests__/use-scroll-hander.test.ts
src/table/components/virtualized-table/hooks/use-scroll-handler.ts
src/table/components/virtualized-table/types/index.ts

First part in consuming the constraints from nebula. This PR removes the pagination and disable scrolling given that the `active` constraint is `true`.

feat: use constraints in vt mode

---

src/ext/property-panel/settings.js

add visibility button group for chart exploration

feat: visibility toggle

---

src/locale/locales/de.json
src/locale/locales/es.json
src/locale/locales/fr.json
src/locale/locales/it.json
src/locale/locales/ja.json
src/locale/locales/ko.json
src/locale/locales/nl.json
src/locale/locales/pl.json
src/locale/locales/pt.json
src/locale/locales/ru.json
src/locale/locales/sv.json
src/locale/locales/tr.json
src/locale/locales/zh-CN.json
src/locale/locales/zh-TW.json

chore(translations): UI bus - 2023-01-13
- Update translations related to: d072aa4 - feat: Search feature in columns dropdown menu (#788)

chore(translations): UI bus - 2023-01-13

---

src/table/components/virtualized-table/__tests__/Table.spec.tsx
src/table/components/virtualized-table/hooks/use-selector.ts

Adds a check for constraints in vt mode before enabling selections

feat: check if selections is enabled

---

src/ext/property-panel/settings.js
src/index.ts
src/types.ts

Enables the user to toggle pagnination mode ON/OFF. Default is ON and toggle is hidden behind a feature flag.

feat: use pagination property

---

src/__test__/test-with-providers.tsx
src/index.ts
src/table/Root.tsx
src/table/components/TableWrapper.tsx
src/table/components/__tests__/TableWrapper.spec.tsx
src/table/components/head/HeadCellContent.tsx
src/table/components/head/TableHeadWrapper.tsx
src/table/components/head/__tests__/HeadCellContent.spec.tsx
src/table/components/head/__tests__/TableHeadWrapper.spec.tsx
src/table/components/head/styles.ts
src/table/context/TableContext.tsx
src/table/types.ts
src/table/virtualized-table/HeaderCell.tsx
src/table/virtualized-table/__tests__/Table.spec.tsx
src/table/virtualized-table/types/index.ts

- using `HeadCellContent` inside `HeaderCell`
- moving `changeSortOrder` to context

feat: sorting and head menu in virtual scroll

---

src/table/components/body/TableBodyWrapper.tsx
src/table/components/body/TableTotals.tsx
src/table/components/head/TableHeadWrapper.tsx
src/table/context/TableContext.tsx
src/table/hooks/use-table-styling.ts
src/table/types.ts
src/table/utils/styling-utils.ts
src/table/virtualized-table/Table.tsx
src/table/virtualized-table/Totals.tsx

since font sizes and famalies will be needed for doing a proper "hug" calculation, we need to put the styling on the context

refactor: put table styling on context

---

src/table/components/body/__tests__/TableBodyWrapper.spec.tsx
src/table/components/body/__tests__/TableTotals.spec.tsx
src/table/components/body/__tests__/withColumnStyling.spec.tsx
src/table/components/body/__tests__/withSelections.spec.tsx
src/table/components/head/MenuItems.tsx
src/table/components/head/__tests__/TableHeadWrapper.spec.tsx

When you run unit test some of them logged various errors. This PR attempts to fix the reason behind the errors, thus removing the errors logged.

test: remove errors logged during test

---

src/table/utils/selections-utils.ts
src/table/virtualized-table/Totals.tsx
src/table/virtualized-table/TotalsCell.tsx
src/table/virtualized-table/hooks/__tests__/use-data.test.ts
src/table/virtualized-table/hooks/use-data/utils/index.ts

Fixed isses related to user dragging a dimension column to a different index:
- Single select did not work
- Multicell select did not work
- Totals value did not match column

fix: column sort order issues

---

src/index.ts
src/table/Root.tsx
src/table/context/TableContext.tsx
src/table/virtualized-table/Body.tsx
src/table/virtualized-table/Table.tsx
src/table/virtualized-table/Wrapper.tsx
src/table/virtualized-table/__tests__/Table.spec.tsx
src/table/virtualized-table/__tests__/Wrapper.spec.tsx
src/table/virtualized-table/types/index.ts
src/table/virtualized-table/utils/get-table-data.ts

Fixes an issue where the totals border would not be colored correctly.

fix: totals border color in vt mode

---

src/__test__/test-with-providers.tsx
src/table/components/body/TableBodyWrapper.tsx
src/table/components/body/__tests__/TableBodyWrapper.spec.tsx
src/table/hooks/__tests__/use-selection-listener.spec.ts
src/table/hooks/use-selection-listener.ts
src/table/utils/__tests__/selections-utils.spec.ts
src/table/utils/selections-utils.ts
src/table/virtualized-table/hooks/use-selections-effect.ts

Noticed that while toggling between usePagination a few times an error was logged to console about a possible event memory leak.
Tracked it down to this useEffect that did not properly return the cleanup function.

fix: selection listener memleak

---

src/index.ts
src/nebula-hooks/use-virtualized-table.ts
src/table/Root.tsx
src/table/virtualized-table/types/index.ts

Make the field selection menu work in virtual scroll table

fix: field selection menu in vt mode

---

src/locale/locales/de.json
src/locale/locales/es.json
src/locale/locales/fr.json
src/locale/locales/it.json
src/locale/locales/ja.json
src/locale/locales/ko.json
src/locale/locales/nl.json
src/locale/locales/pl.json
src/locale/locales/pt.json
src/locale/locales/ru.json
src/locale/locales/sv.json
src/locale/locales/tr.json
src/locale/locales/zh-CN.json
src/locale/locales/zh-TW.json

chore(translations): UI bus - 2023-02-14
- Update translations related to: 9387e94 - feat: field base selections in dropdown (#826)

chore(translations): UI bus - 2023-02-14

---

src/table/components/TableWrapper.tsx
src/table/context/TableContext.tsx
src/table/hooks/use-column-widths.ts
src/table/types.ts

Fixes an issue in the pagination table where a horizontal scrollbar would appear just because there was a vertical scrollbar

fix: scrollbar when not needed

---

src/table/virtualized-table/hooks/use-data/index.ts
src/table/virtualized-table/hooks/use-get-hypercube-data-queue.ts

Fixes an issue where the scroll table would sometimes render with empty cells

fix: empty cells on initial render

---

src/locale/locales/de.json
src/locale/locales/es.json
src/locale/locales/fr.json
src/locale/locales/it.json
src/locale/locales/ja.json
src/locale/locales/ko.json
src/locale/locales/nl.json
src/locale/locales/pl.json
src/locale/locales/pt.json
src/locale/locales/ru.json
src/locale/locales/sv.json
src/locale/locales/tr.json
src/locale/locales/zh-CN.json
src/locale/locales/zh-TW.json

chore(translations): UI bus - 2023-02-21
- Update translations related to: 5d9858d - feat: selection actions in sub-menu (#846)

chore(translations): UI bus - 2023-02-21

---

src/ext/property-panel/data.js

feat: add accordion to side property panel

---

src/__test__/handle-data.spec.ts
src/handle-data.ts
src/table/components/head/HeadCellMenu.tsx
src/table/components/head/__tests__/HeadCellContent.spec.tsx
src/table/components/head/__tests__/HeadCellMenu.spec.tsx
src/table/hooks/__tests__/use-field-selection.spec.tsx
src/table/hooks/use-field-selection.ts
src/types.ts

this pr makes the listbox available for master dims
**we need to wait for a nebula bump ([this PR should be in that release](https://github.com/qlik-oss/nebula.js/pull/1088))**
---
https://user-images.githubusercontent.com/29652890/221845297-4757ea9d-9116-40e0-9a76-3023c78850e6.mov

feat: listbox for master dims

---

src/ext/property-panel/data.js

There is one related PR in sense-client to support this

feat: add number formatting and limits in property panel

---

src/__test__/handle-data.spec.ts
src/handle-data.ts

The first if checks if it is a measure, meaning we only need to check if the column is the one furthest left, which is pageColIdx === 0

fix: totals label on first col

---

src/__test__/handle-data.spec.ts
src/ext/property-panel/data.js
src/ext/property-panel/settings.js
src/handle-data.ts
src/nebula-hooks/use-pagination-table.ts
src/table/pagination-table/components/body/TableBodyWrapper.tsx
src/table/pagination-table/components/body/TableTotals.tsx
src/table/pagination-table/components/body/__tests__/TableBodyWrapper.spec.tsx
src/table/pagination-table/components/body/__tests__/TableTotals.spec.tsx
src/table/types.ts
src/table/utils/__tests__/handle-keyboard.spec.ts
src/table/utils/handle-keyboard.ts

Realized that we were passing the flag to the keyboard handler for totals, that totals is not behind flag. This should fix that

fix: put totals behind flag

---

src/table/utils/styling-utils.ts

change default background to white for cells in header

fix: default tHead cell background to white

---

src/handle-data.ts
src/table/utils/styling-utils.ts
src/table/virtualized-table/hooks/use-data/utils/index.ts

my idea with extracting the logic was to put all the logic in the same place

refactor: put cell align logic in one place

---

src/locale/locales/de.json
src/locale/locales/es.json
src/locale/locales/fr.json
src/locale/locales/it.json
src/locale/locales/ja.json
src/locale/locales/ko.json
src/locale/locales/nl.json
src/locale/locales/pl.json
src/locale/locales/pt.json
src/locale/locales/ru.json
src/locale/locales/sv.json
src/locale/locales/tr.json
src/locale/locales/zh-CN.json
src/locale/locales/zh-TW.json

chore(translations): UI bus - 2023-03-10
- Update translations related to: efd9bb9 - feat: use keyboard to resize column (#886)

chore(translations): UI bus - 2023-03-10

---

src/table/components/head/ColumnAdjuster.tsx

some border mis calc were fixed in this PR from column adjuster => which was the root cause of issue!

fix: scroll to infinity in firefox

---

nebula.config.js
src/ext/property-panel/__test__/settings.spec.js
src/ext/property-panel/settings.js
src/nebula-hooks/use-extended-theme.ts
src/table/utils/styling-utils.ts
test/rendering/table-test-theme.render.ts
test/rendering/theme/sense-horizon.js
theme/sense-dark-horizon.js

Switching the keyword for the theme from `straightTable` to `straightTableV2`

feat: use new theme entry

---

src/ext/property-panel/data.js

feat: add show others checkbox

---

spec-configs/props.conf.js
src/qae/object-properties.js

- update from experimental to stable
- remove columnWidths
- usePagination is optional
- totals and its properties are optional
- fix percentage description
Syntax reference: https://jsdoc.app/tags-type.html

feat: update api spec

---

src/locale/locales/de.json
src/locale/locales/es.json
src/locale/locales/fr.json
src/locale/locales/it.json
src/locale/locales/ja.json
src/locale/locales/ko.json
src/locale/locales/nl.json
src/locale/locales/pl.json
src/locale/locales/pt.json
src/locale/locales/ru.json
src/locale/locales/sv.json
src/locale/locales/tr.json
src/locale/locales/zh-CN.json
src/locale/locales/zh-TW.json

chore(translations): UI bus - 2023-04-14
- Update translations related to: 5b494cf - fix: add signatures for strings (#980)
- Update translations related to: 22d934d - fix: add translations to ascending and descending (#939)

chore(translations): UI bus - 2023-04-14

---

src/table/pagination-table/components/body/TableBodyWrapper.tsx
src/table/utils/styling-utils.ts
src/table/virtualized-table/Body.tsx
test/rendering/__fixtures__/scenario_10.fix.js
test/rendering/__fixtures__/scenario_10_scroll.fix.js
test/rendering/__fixtures__/scenario_11.fix.js
test/rendering/__fixtures__/scenario_11_scroll.fix.js
test/rendering/__fixtures__/scenario_12.fix.js
test/rendering/__fixtures__/scenario_13.fix.js
test/rendering/__fixtures__/scenario_13_scroll.fix.js
test/rendering/__fixtures__/scenario_4.fix.js
test/rendering/__fixtures__/scenario_4_scroll.fix.js
test/rendering/__fixtures__/scenario_9.fix.js
test/rendering/__fixtures__/scenario_9_scroll.fix.js

making sure the hover color is using the correct reference. Also updating the rendering tests, since this should be closer to what the props are in sense.

fix: hover colors

---

.circleci/config.yml
.github/CONTRIBUTION.md
package.json
yarn.lock

- Check duplicated packages in CI
- Check duplicated packages in "lint-staged"
- Add yarn-deduplicat as a devDep and a script for it that fixes the issues

chore: check duplicated packages in CI

---

tools/build.js

to accommodate https://github.com/qlik-oss/nebula.js/commit/b64a8133f42fe9842ebcf503752084799fc1d943

chore: fix nebula dev build without systemjs

---

src/ext/index.js
src/handle-data.ts
src/index.ts
src/nebula-hooks/use-pagination-table.ts
src/table/hooks/use-snapshot.ts
src/table/hooks/use-view-service.ts
src/table/pagination-table/components/TableWrapper.tsx
src/table/pagination-table/components/__tests__/TableWrapper.spec.tsx
src/table/types.ts
src/types.ts

This PR is to support download as image/pdf for pagination table

feat: support download as image/pdf

---

src/locale/locales/de.json
src/locale/locales/es.json
src/locale/locales/fr.json
src/locale/locales/it.json
src/locale/locales/ja.json
src/locale/locales/ko.json
src/locale/locales/nl.json
src/locale/locales/pl.json
src/locale/locales/pt.json
src/locale/locales/ru.json
src/locale/locales/sv.json
src/locale/locales/tr.json
src/locale/locales/zh-CN.json
src/locale/locales/zh-TW.json

chore(translations): UI bus - 2023-07-07
- Update translations related to: 556c195 - fix: add aria-label for head menu button (#1036)

chore(translations): UI bus - 2023-07-07

---

src/table/hooks/__tests__/get-view-state.spec.ts
src/table/hooks/__tests__/use-snapshot.spec.ts
src/table/hooks/use-snapshot.ts

To fix a mistake from https://github.com/qlik-oss/sn-table/pull/1035 which broke sn-table down load on qcs.

fix: fix missing parameter

---

src/__test__/generate-test-data.ts
src/nebula-hooks/__tests__/use-announce-and-translations.spec.ts
src/nebula-hooks/use-announce-and-translations.ts
src/table/components/footer/PaginationContent.tsx
src/table/components/head/ColumnAdjuster.tsx
src/table/pagination-table/components/AnnounceElements.tsx
src/table/pagination-table/components/__tests__/AnnounceElements.spec.tsx
src/table/utils/accessibility-utils.ts

all ID's attributes in the DOM should be unique, this is the first batch of fixing those, more to come

fix: easy id fixes

---

src/table/components/head/ColumnAdjuster.tsx
src/table/components/head/__tests__/ColumnAdjuster.spec.tsx
src/table/components/head/styles.ts

- adding event listeners for `touchstart`, `touchmove,` `touchend`. Using the same logic just slightly different event structure -> we need separate handle functions

fix: add touch listeners for ColumnAdjuster

---

package.json
src/table/components/head/styles.ts
src/table/utils/accessibility-utils.ts
yarn.lock

addresses this PR thread: https://github.com/qlik-oss/sn-table/pull/1084#discussion_r1387976031
need this to be merged + released first: https://github.com/qlik-oss/nebula-table-utils/pull/78

chore: use exposed class name instead of id for headCellMenuButton

---

package.json
src/table/pagination-table/components/TableWrapper.tsx
src/table/utils/accessibility-utils.ts
yarn.lock

when trying to focus on col adjuster (using keyboard or hitting on the col adjuster menu item) it fails to find the correct element (the adjuster blue needle)
this is due to a class name change we had a while ago, so this PR uses that exact class name and fixes the issue

fix: miss while trying to find col adjuster hit area

---

package.json
src/table/components/head/HeadCellContent.tsx
yarn.lock

this PR needs this one to be released first: https://github.com/qlik-oss/nebula-table-utils/pull/85

chore: remove tab index prop from hamburger menu button

---

package.json

Adding max lint warnings in here. Would be nice to keep this to a minimum

chore: add max lint warnings

---

package.json
src/table/components/head/HeadCellContent.tsx
src/table/components/head/HeadCellMenu.tsx
src/table/hooks/__tests__/use-column-widths.spec.ts
src/table/hooks/use-column-widths.ts
src/table/pagination-table/components/body/styles.ts
src/table/styling-defaults.ts
src/table/utils/accessibility-utils.ts
src/table/virtualized-table/TotalsCell.tsx
src/table/virtualized-table/hooks/__tests__/use-dynamic-row-height.spec.tsx
src/table/virtualized-table/hooks/use-dynamic-row-height.ts
src/table/virtualized-table/hooks/use-heights.ts
yarn.lock

- use new prop for header menu
- new props structure for useMeasreText

chore: use new version of nebula-table-utils
