qlik-oss/sn-table

package.json, yarn.lock
As optional deps are treated as actual deps after build, I need to move them into devDeps. This way they won't show up in installed sn-tables in other projects (as they are bundled). Still a bit unsure how externals should handle this, so I'll keep the rollup logic.
=> chore: move sprout deps to devDeps

package.json, rollup.config.js, yarn.lock
Need this to get it to transpile away those `object?.optionalProp` things. Discovered when running linked with nebula.
=> chore: add optional chaining transpiler

.codeclimate.yml
similar-code threshold describes the mass code block to be analyzed for duplication.
Refer https://github.com/codeclimate/codeclimate-duplication
for this settings.
=> Fix similar code checking in codeclimate

src/table/TableBodyWrapper.jsx, src/table/__tests__/TableWrapper.spec.jsx
react skip render TableBodyWrapper when no  prop changes and add dependencies to use Memo otherwise a new value will be computed on every render
=> table body performance

src/table/TableBodyWrapper.jsx
a quick fix. will look into https://material-ui.com/styles/basics/#material-ui-styles and https://material-ui.com/customization/theming/ to use the theme. 
Not sure if rollup-plugin-postcss is in use.
=> fix cell focus style

src/mui-setup.js, src/table/TableBodyWrapper.jsx, src/table/TableHeadWrapper.jsx, src/table/__tests__/styling-utils.spec.js, src/table/styling-utils.js
Moving a bunch of static css to the theme.
Also found two bugs and fixed them:
- The hover wasn't updating when changing colors. JSS prefers a different syntax.
- There was a double hover border. It should be the inset one only.
=> fix: proper focus styling + refactor

src/table/TableWrapper.jsx, src/table/__tests__/TableWrapper.spec.jsx
fixes #165
It only reads this when focusing into the table, so not for every cell.
=> feat: announcing number of rows and columns when entering table

src/mui-setup.js, src/table/TableWrapper.jsx
There was a reason for that lint issue, can't use the package in the mashup when you have multiple keys on an object apperently.
=> fix: revert header scroll fix

src/mui-setup.js
Numbers at the start of css classnames are not allowed. This works in general, but breaks in some browsers, better keep it safe.
=> fix: avoid numbers at start of class

src/table/TableBodyWrapper.jsx
=> feat(a11y): the screen reader should always says the column name first and then the row content

src/table/TableBodyWrapper.jsx, src/table/TableHeadWrapper.jsx, src/table/__tests__/TableBodyWrapper.spec.jsx, src/table/__tests__/TableHeadWrapper.spec.jsx, src/table/__tests__/TableWrapper.spec.jsx, src/table/cells/__tests__/handle-key-press.spec.js, src/table/cells/__tests__/renderer.spec.js, src/table/cells/__tests__/withColumnStyling.spec.jsx, src/table/cells/__tests__/withSelections.spec.jsx, src/table/cells/__tests__/withStyling.spec.jsx
this is a quick PR for updating the way we use sinon in our test files
it's more refinement to our test cases rather than developing some feature or fixing a bug!
=> [chore]: fully moved to use `sinon.stub` instead of `sandbox.replace`

src/table/cells/__tests__/handle-key-press.spec.js, src/table/cells/handle-key-press.js
in this PR, I have tweaked the functionality for `arrowKeysNavigation` a bit in order to support the row navigation when reaching to the end or beginning of each row in table. 
also since the only purpose of this PR is to navigate between rows in table there are two constrains for it: 
1. **when we reach to the beginning of the table (`[0, 0]` coordinates)**
2. **when we reach to the end of the table (`[rowLenght - 1, colLength - 1]` coordinates)**
in those cases we are still making user to remain in those cells until they actually want to move to the next element by using `shift + tab` in order to move to the previous focused element or by just using `tab` in order to move to the next element on the screen.
=> [fix/#161]: fixed table navigation move to the next/previous line

src/table/cells/handle-key-press.js
`selState && selState.rows.length > 0;` to check if you have unconfirmed selections, so one or more cells are selected but not confirmed yet.
I feel it have the same meaning with selectionsAPI.isModal(), but selectionsAPI is a react hook and can't be used in regular JavaScript functions..
=> fix: variable name confusion

src/table/TableWrapper.jsx, src/table/__tests__/TableWrapper.spec.jsx
fixes #261 
it looks like we miss the `tabIndex` on our `<TableWrapper />` component. it will does the job.
=> [FIX#261]: fixed double tab to focus in firefox

src/table/cells/__tests__/handle-key-press.spec.js, src/table/cells/handle-key-press.js
=> fix: table loses focus in an embedded sheet after pressing ctrl+shift+left or right arrow to change page

src/table/TableWrapper.jsx
when we have some selections, and trying to change the page, focus should stay on the very first cell of the same column. 
this PR fixes that 
fixes #301
=> reset focus on change page

src/table/components/TableWrapper.jsx
need to use tabindex in `<select>` component in mui v4.
in mui v5, it was fixed.
=> fix: should use tabIndex

.eslintrc.json, src/index.js
just found that eslint-plugin-react-hooks was already installed, but the eslint rule is not added.
=> feat: add react hook ESLint rule

src/table/components/TablePaginationActions.jsx
Invalid prop `tabIndex` of type `string` supplied to `ForwardRef(ButtonBase)`, expected `number`. I thought it was fixed before, but just a minor issue.
=> fix: the type of value supplied to tabIndex is wrong

src/__test__/generate-test-data.js, src/__test__/handle-data.spec.js, src/__test__/sorting-factory.spec.js, src/handle-data.js, src/index.js, src/table/components/TableWrapper.jsx, src/table/components/__tests__/TableBodyWrapper.spec.jsx
- When there is more than 100 columns you can't change the rows per page manually
- Set height to the smallest possible value. On the last page we always fetched with `qHeight: rowsPerPage` even though there was usually fewer rows
- When there are > 10k cells, set rows per page to a lower options, e.g. 150 cols, 100 rows -> 150 cols, 25 rows. If the lowest option is too high (10 currently, meaning > 1000 columns...) It is set to 10k / columns.
I have tested with > 100 columns, but not > 1000.
=> fix: make sure page for getHyperCubeData is never more than 10k cells

src/locale/locales/de.json, src/locale/locales/es.json, src/locale/locales/fr.json, src/locale/locales/it.json, src/locale/locales/ja.json, src/locale/locales/ko.json, src/locale/locales/nl.json, src/locale/locales/pl.json, src/locale/locales/pt.json, src/locale/locales/ru.json, src/locale/locales/sv.json, src/locale/locales/tr.json, src/locale/locales/zh-CN.json, src/locale/locales/zh-TW.json
feat(translations): UI bus - 2021-12-03
- Update translations related to: 5eb4abf - fix: add missing key to check if translated string is different from its id (#378)
- Update translations related to: 31ce77b - feat: add navigatio instructions for SR
- Update translations related to: a18e2cc - Revert "feat: add navigatio instructions for SR"
- Update translations related to: 0ff4c3e - [FIX#315]: SR announcements for pagination part of the table
- Update translations related to: cec6214 - feat: add navigation instructions for SR (#401)
=> feat(translations): UI bus - 2021-12-03

src/__test__/generate-test-data.js, src/__test__/handle-data.spec.js, src/__test__/sorting-factory.spec.js, src/handle-data.js, src/index.js, src/sorting-factory.js, src/table/components/TableHeadWrapper.jsx, src/table/components/__tests__/TableHeadWrapper.spec.jsx, src/table/utils/__tests__/handle-key-press.spec.js, src/table/utils/handle-key-press.js
- Remove the dependency of the `columnOrder` array outside `manageData`. Keep the "data" index of the column in the column info instead
- Use the column sort order from the properties instead of layout. `layout.qEffectiveInterColumnSortOrder` doesn't contain hidden column, thus it's ending the wrong thing in the patches. Fetching the properties makes the sorting function asynchronous, but that shouldn't matter
=> fix: remove hidden column from columnOrder

.github/CONTRIBUTION.md, package.json
Based on @cbt1's changes for mekko, `yarn spec` is added to run at the same time as version. Build  runs before to make sure the build step wont fail on Circle. Also extending the instructions a bit.
=> chore: run `yarn spec` on npm version

src/table/components/TableBodyWrapper.jsx, src/table/components/__tests__/TableBodyWrapper.spec.jsx, src/table/components/__tests__/withSelections.spec.jsx, src/table/components/withColumnStyling.jsx, src/table/components/withSelections.jsx, src/table/components/withStyling.jsx
a better way to fix the react warnings about dom attributes
`selectionState`, `selDispatch`, `announce`, `cell`, `column`, and `value` are not needed to be attached in the dom.
=> refactor: unnecessary tablecell props cleanup

src/table/components/TableBodyWrapper.jsx, src/table/components/TablePaginationActions.jsx, src/table/components/TableWrapper.jsx, src/table/components/__tests__/TableBodyWrapper.spec.jsx, src/table/components/__tests__/withSelections.spec.jsx, src/table/components/renderer.js, src/table/components/withColumnStyling.jsx, src/table/components/withSelections.jsx, src/table/components/withStyling.jsx, src/table/utils/__tests__/handle-key-press.spec.js, src/table/utils/__tests__/selections-util.spec.js, src/table/utils/handle-key-press.js, src/table/utils/selections-utils.js
1. React does not like capital letters. Updating all props names into lowercase
2. Renaming `selDispatch` to `selectionDispatch`
3. `tableData.columns` to be `columns`
4. `onPageChange` is required in `TablePagination`
5. Adding unique key for `<option>`
No solution for the last warning yet
More to read:
https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html#changes-in-detail
=> refactor: rename and fix warnings

src/handle-data.js, src/locale/src/index.js, src/table/components/TableBodyWrapper.jsx, src/table/components/TableHeadWrapper.jsx, src/table/components/__tests__/TableHeadWrapper.spec.jsx, src/table/components/withSelections.jsx, src/table/utils/__tests__/handle-key-press.spec.js, src/table/utils/__tests__/selections-util.spec.js, src/table/utils/__tests__/styling-utils.spec.js, src/table/utils/handle-accessibility.js, src/table/utils/selections-utils.js, src/table/utils/styling-utils.js
When you set the color of header content, the color of the sort label should be the same as that.
When there is no header content color setting, the sort label color is kind of white in the dark background color and black in the light background color.
=> feat: adjust the sort label color based on the header background color

src/table/utils/__tests__/styling-utils.spec.js, src/table/utils/styling-utils.js
Allow developers to provide custom padding for table headers and cells by overriding baseStyling in the same way color and fontSize can be overridden.
=> Feat: allow padding override of cells

.github/CONTRIBUTION.md, test/rendering/README.md, test/rendering/scripts/run-rendering-test.sh, test/rendering/scripts/update-screenshots.sh
when the playwright is updated, the script file is broken.
=> chore: sync playwright version between installed package and script files

package.json, src/table/components/TablePaginationActions.jsx
```
Array()
.fill()
.map((_, index) => ())
```
_ is undefined which causes warnings and impacts performance.
=> fix: undefined keys for select page

src/__test__/table-theme-colors.spec.js, src/index.js, src/table-theme-colors.js
Checking that the table is actually a child of the object/sheet before we get the computed styles from it.
Also took the liberty of rewriting the tests a bit. No need to reset mocked functions every tests, the logic stays the same and then you just changes the variable that the function returns.
=> fix: check if table is inside object and sheet when getting computed styles

src/table/utils/__tests__/handle-key-press.spec.js, src/table/utils/handle-key-press.js
- The cmd+shift+arrow command to change page bc of a argument mismatch
- Also an argument with the wrong name resulting in that you could navigate to header in selection mode
=> fix: next page command and block header to focus in selections

src/table/components/TableHeadWrapper.jsx, src/table/components/__tests__/TableHeadWrapper.spec.jsx, src/table/utils/__tests__/handle-accessiblity.spec.js, src/table/utils/__tests__/styling-utils.spec.js, src/table/utils/handle-accessibility.js, src/table/utils/styling-utils.js
- When clicking TableSortLabel, it gets focused instead of the header cell.
So adding an explicit click method to TableSortLabel adds focus to the header cell.
- Add a cursor to the head cell
=> fix: clicking the header cell does not always sets the focus

src/table/components/TableBodyWrapper.jsx
Fix #571,  when you exit selection mode, pressing ESC in selection mode blurs everything.
whenever the layout updates, `manageData` will run and there will be a new instance of `columns`, which triggers the effect to be executed, which means we get new column renderers and the cells lose their reference, thus losing focus.
=> fix: pressing esc in selection mode blurs everything

src/table/components/TableWrapper.jsx, src/table/utils/__tests__/handle-key-press.spec.js, src/table/utils/__tests__/handle-scroll.spec.js, src/table/utils/handle-key-press.js, src/table/utils/handle-scroll.js
Head:
when a focused cell is updated, the scroll position is updated accordingly.
Current:
only when using the keyboard to move up, the scroll position is updated accordingly
https://user-images.githubusercontent.com/4471489/183973096-02159b34-3100-4c7b-80e1-58b718798e20.mov
Limitation:
For a very narrow table, the best we can do is that arrow up scroll behavior is the same as the arrow down scroll behavior
Head:
https://user-images.githubusercontent.com/4471489/183924745-1f1c290b-405a-46bb-8bf1-590a0b49d4ef.mov
Current:
https://user-images.githubusercontent.com/4471489/183974003-9cf9f391-8441-4fa5-82d9-12afa8a91673.mov
=> fix: table moves up when doing selection

src/table/utils/handle-key-press.js
Broken by me from a refactor a while back. We break if topAllowedRow > 0, and it was undefined when moving left/right
=> fix: block left/right movement in selection mode

src/index.ts, src/nebula-hooks/use-announce-and-translations.ts, src/nebula-hooks/use-extended-theme.ts, src/nebula-hooks/use-react-root.ts, src/nebula-hooks/use-sorting.ts
Migrate from
```
const [filteredData, setFilteredData] = useState();
useEffect(() => {
setFilteredData(data.filter(x => isOfSomeType(x)));
}, [data]);
return <List data={filteredData} />;
```
to it
```
const filteredData = useMemo(() => {
return data.filter(x => isOfSomeType(x));
}, [data]);
return <List data={filteredData} />;
```
Reference: https://jnystad.no/post/not-using-usecallback-is-premature-optimization
=> refactor: migrate custom hook pattern

src/__test__/handle-data.spec.ts, src/table/styles.ts, src/table/utils/__tests__/handle-accessiblity.spec.ts, src/table/utils/__tests__/handle-key-press.spec.ts, src/table/utils/__tests__/selections-util.spec.ts, src/table/utils/handle-accessibility.ts, src/table/utils/selections-utils.ts, src/types.ts
This was conflicting with mui TableCell and more aligned with the naming of `Column` and `Rox`.  Also fixed the imports for styles file
=> refactor: rename TableCell type to Cell

src/table/utils/__tests__/handle-key-press.spec.ts, src/table/utils/handle-key-press.ts
This bubbled to somewhere and made the focus go left for some reason.
=> fix: block ArrowUp on header

src/table/components/TableBodyWrapper.tsx, src/table/components/TableWrapper.tsx, src/table/components/__tests__/TableBodyWrapper.spec.tsx, src/table/types.ts
Previously the totals component was passed as a child to the body. This was to reduce props drilling. Totals is memoed using React.memo and it used to work works. This is what the profiler looks like, the totals don't rerender when the body does. But it is the children property that makes the body update (I have a snippet to test this). Feels really backwards to me, but maybe that is how is should work. Anyway, adding totals inside the body component instead, works!
=> fix: move total to reduce rerenders

tools/build.js
`const watcher = await build(buildArgs);` already does the build step
when not in reactNative build, no need to run `build(buildArgs)` again.
=> chore: remove extra nebula build

src/table/components/TableBodyWrapper.tsx, src/table/components/TableHeadWrapper.tsx, src/table/components/TableTotals.tsx, src/table/components/TableWrapper.tsx, src/table/components/__tests__/PaginationContent.spec.tsx, src/table/components/__tests__/TableBodyWrapper.spec.tsx, src/table/components/__tests__/TableHeadWrapper.spec.tsx, src/table/components/__tests__/TableTotals.spec.tsx, src/table/hooks/use-focus-listener.ts, src/table/utils/__tests__/accessiblity-utils.spec.ts, src/table/utils/__tests__/handle-click.spec.ts, src/table/utils/__tests__/handle-key-press.spec.ts, src/table/utils/accessibility-utils.ts, src/table/utils/handle-click.ts, src/table/utils/handle-key-press.ts
Mostly moving code here, no need to look at any logic changes. Changed the tests for the click functions, now only testing with a mocked function. Also added two simple tests for `removeTabAndFocusCell`
- handle-accessibility -> accessibility-utils, it is almost no actual handles in there
- `handleResetFocus` -> `resetFocus`, not an event handler
- `removeAndFocus` -> `removeTabAndFocusCell`. Remove and focus what? I think this is better
- introduce handle-click. Move all click handlers there
- move focus-only related functions to accessibility-utils, since they don't really have anything to do with pressing a key (`getNextCellCoord` and `moveFocus`)
So what needs to reviewed properly is the changes in tests and the new comments
=> refactor: break out click functions to seperate file and move focus stuff to a11y file

src/table/utils/__tests__/accessiblity-utils.spec.ts, src/table/utils/accessibility-utils.ts
When clicking a cell to focus it, you remove the tab-index for the one the cell that has a tab stop already. When keyboard.focus does not run, the tab-index is still -1 for the new focused cell. Need to make sure it is added manually.
=> fix: properly focus cell on click

package.json
lint-staged ignores tsconfig.json when tsc called through git hooks, using a `bash -c` trick
Reference: https://github.com/okonet/lint-staged/issues/825
=> feat: checking types when committing

src/handle-data.ts, src/table/utils/__tests__/handle-key-press.spec.ts, src/table/utils/__tests__/selections-utils.spec.ts, src/table/utils/handle-key-press.ts, src/table/utils/selections-utils.ts, src/types.ts
Since we now store `allRows` on the selection state, no need to store qElemNumber for any neighboring cells on the cell. Replacing with a last row bool, to keep track of when it is bossible to select by shift + arrow down. also:
- use KeyCodes in test file
- breaking out `shouldSelectMultiValues` for readability in `handleBodyKeyPress`
=> refactor: remove prev/next qElemNumber

src/nebula-hooks/use-context-menu.ts
Seems like it is possible to load the sn-table on the fly and the peerDependencies are not enforced, leading to the table crashing. This is just to make sure it doesn't
=> fix: sanity check to avaoid crash on old nebula versions

src/nebula-hooks/use-context-menu.ts, src/table/components/TableBodyWrapper.tsx, src/table/components/TableHeadWrapper.tsx, src/table/components/TableTotals.tsx, src/table/components/__tests__/TableHeadWrapper.spec.tsx, src/table/components/__tests__/TableTotals.spec.tsx, src/table/types.ts, src/table/utils/__tests__/accessiblity-utils.spec.ts, src/table/utils/__tests__/handle-key-press.spec.ts, src/table/utils/accessibility-utils.ts, src/table/utils/handle-key-press.ts, src/types.ts
CopyCellValue via keyDown ( `ctrl + c ` and `meta + c` ) is functioning now on Head and Total cells as well as body cells.
=> feat: extend copyCellValue via keyDown to Heads and Total cells

src/ext.js
moving this outside the pp definition, since it doesn't really make sense to have it live next to the definition of actual pp components.
=> refactor: move exploration definition

src/table/utils/__tests__/handle-key-press.spec.ts, src/table/utils/handle-key-press.ts, src/table/utils/selections-utils.ts
To reduce risk of arrow key events being picked up at higher levels. This is sometimes used to navigate between charts on a "sheet". Without stopping the propagation, this could potentially make you lose focus when you intended to stay inside the table. pagination specifically since it has no listener for arrows
=> fix: block arrow keys from propagating

src/__test__/generate-test-data.ts, src/__test__/handle-data.spec.ts, src/handle-data.ts, src/table/Root.tsx, src/table/components/TableBodyWrapper.tsx, src/table/components/__tests__/TableBodyWrapper.spec.tsx, src/table/constants.ts, src/table/context/TableContext.tsx, src/table/types.ts, src/table/utils/__tests__/handle-click.spec.ts, src/table/utils/__tests__/handle-key-press.spec.ts, src/table/utils/__tests__/selections-utils.spec.ts, src/table/utils/handle-click.ts, src/table/utils/handle-key-press.ts, src/table/utils/selections-utils.ts, src/types.ts
Was using the wrong column index. Was really confused by the which one is which, so I renamed them
- rawCol/RowIdx -> pageCol/RowIdx. raw never made sense to me since raw could refer to the raw data, meaning the entire data set. page refers dataPage, so row 0 is the first row that we are actually showing atm
- allRows -> pageRows. Same terminology, it is all rows on the dataPage
=> fix: correct index usage for select multiple

src/index.ts, src/nebula-hooks/__tests__/use-sorting.spec.ts, src/nebula-hooks/use-sorting.ts, src/table/components/TableHeadWrapper.tsx, src/table/components/__tests__/TableHeadWrapper.spec.tsx, src/table/context/TableContext.tsx, src/table/hooks/use-selection-reducer.ts, src/table/types.ts, src/table/utils/__tests__/handle-key-press.spec.ts, src/table/utils/handle-key-press.ts, src/types.ts
Noticed some things we could clean up.
- wrap the selection reducer in a hook. Will ad more stuff to TableContext so want to keep it clean
- not passing layout to sorting. When it changes we rerender from root, so we can add the hypercube in the factory
=> refactor: align hooks

src/__test__/handle-data.spec.ts, src/handle-data.ts, src/nebula-hooks/__tests__/use-sorting.spec.ts, src/nebula-hooks/use-sorting.ts, src/table/components/TableBodyWrapper.tsx, src/table/components/TableHeadWrapper.tsx, src/table/components/__tests__/TableHeadWrapper.spec.tsx, src/table/components/__tests__/TableTotals.spec.tsx, src/types.ts
The data structure for `rows` has been unchanged since the prototype. I've been confused with this a million times. Aligning things so hopefully it will be easier in the future. This enabled me to do some rewrites in handle-data
- the order of columns in `rows` is the order they will be shown in, now this aligns with `columns`
- store both types of indexes in columns and cells. `col/rowIdx` is index in the entire dataset, not necesarilly what is rendered. `pageRow/ColIdx` is the index in the displayed page
- simplify `getTotalInfo` and `getTotalPosition`
- add comments for all functions in handle-data
- remove `width` from `Column` type since it was never used. Will add other width stuff here for the column resize
- removed `getColumnOrder` and put the logic in `getColumns` together with …
=> refactor: put rows in order it should be rendered

package.json
similar to https://github.com/qlik-oss/sn-table/pull/704
eslint ignores configurations when eslint is called through git hooks, using a bash -c trick
=> chore: lint files when committing

src/table/components/virtualized-table/TableContainer.tsx, src/table/components/virtualized-table/hooks/__tests__/use-columns-size.test.ts, src/table/components/virtualized-table/hooks/__tests__/use-measure-text.test.ts, src/table/components/virtualized-table/hooks/use-column-size.ts, src/table/components/virtualized-table/hooks/use-measure-text.ts
There was an issue with how the column width was calculated. It could give the wrong size when all the available space was filled, but the `fillWidth` value was largar then the measure width.
Also the the hard-coded value of 25 that was added to the measured width, was not enough to account for cell padding of 28px.
=> fix: column width calc

src/table/components/virtualized-table/Body.tsx, src/table/components/virtualized-table/Header.tsx
Fixes an issue where the table in vt mode would not resize the columns if the rect from nebula changed. Ex. if a user changed the size of the browser window so that it became larger, the columns would not become larger before this fix.
=> fix: resize colum width on rect change in vt mode

package.json, src/table/components/head/HeadCellMenu.tsx, src/table/components/head/__tests__/HeadCellMenu.spec.tsx, src/table/components/head/__tests__/TableHeadWrapper.spec.tsx, src/table/components/head/styles.ts, yarn.lock
Issues that are fixed:
- Clicking the button does not close the context menu if it is already open.
- Showing menu button when the head cell is hovered or focused
- Making selection on menu-item doesn't close the menu
After fix:
- Clicking the menu button should open the menu as well as closing it.
- Hovering, focusing, clicking the head cell appears the menu button
- Menu will be closed as soon as a menu item is clicked
=> fix: closing menu by clicking head cell causes sorting order

src/nebula-hooks/__tests__/use-extended-theme.spec.ts, src/nebula-hooks/use-extended-theme.ts, src/table/components/TableWrapper.tsx, src/table/components/__tests__/TableWrapper.spec.tsx, src/table/components/body/TableBodyWrapper.tsx, src/table/components/body/__tests__/TableBodyWrapper.spec.tsx, src/table/components/body/__tests__/TableTotals.spec.tsx, src/table/components/footer/FooterWrapper.tsx, src/table/components/footer/PaginationContent.tsx, src/table/components/footer/__tests__/PaginationContent.spec.tsx, src/table/components/footer/styles.ts, src/table/components/head/__tests__/TableHeadWrapper.spec.tsx, src/table/components/styles.ts, src/table/components/virtualized-table/Wrapper.tsx, src/table/components/virtualized-table/__tests__/TableContainer.spec.tsx, src/table/components/virtualized-table/__tests__/Wrapper.spec.tsx, src/table/types.ts, src/table/utils/__tests__/styling-utils.spec.ts, src/table/utils/color-utils.ts, src/table/utils/styling-utils.ts, src/types.ts
The extended theme hook calculated things that we normally do in the styling-utils. I moved everything that is not related to calculating the background out of use-extended-theme. Still keeping the background stuff there since we want it centralized on the theme
- rename `tableThemeColors` to `getBackgroundColors` and store the result under `background` on the extended theme
- remove `background` from the varialbe names inside that funciton, since it is implied that we are talking about background
- create `getFooterStyle` to align with body and header
- added some descriptions for the color utils
=> refactor: move non-background styling from extendedTheme to styling-utils

src/index.ts
`useSelections` can actually initially return null. We need to make sure it is defined when rendering and sanity check for it when checking `isModal`
=> fix: sanity check for selections api

src/table/components/head/HeadCellMenu.tsx, src/table/components/head/TableHeadWrapper.tsx, src/table/components/head/__tests__/HeadCellMenu.spec.tsx, src/table/utils/__tests__/handle-click.spec.ts, src/table/utils/handle-click.ts
Menu sort option will be disabled if the current column is already ordered in the same sort direction.
In the case that the sorting priority is not on the current column, both sort options stays enable until one of them be chosen.
=> feat: disable sortItem when column sort direction is the same

package.json, yarn.lock
Explicity set `@types/react` as a dep. Before it was added as a dependecy via `@types/react-native`.
Possible fix to allow us to merge #770. Should probably have it anyway as `@mui/material` have it as a peer dependency.
=> chore: add @types/react as dev dep

renovate.json
Lock the version for `@nebula.js/cli-build` due to the issue described here #746
=> chore: lock nebula build version

src/__test__/handle-data.spec.ts, src/handle-data.ts, src/nebula-hooks/__tests__/use-sorting.spec.ts, src/nebula-hooks/use-sorting.ts, src/table/components/head/HeadCellMenu.tsx, src/table/components/head/TableHeadWrapper.tsx, src/table/components/head/__tests__/HeadCellMenu.spec.tsx, src/table/components/head/__tests__/TableHeadWrapper.spec.tsx, src/table/components/head/styles.ts, src/table/utils/styling-utils.ts, src/types.ts
- the current sort direction already exists on the column, might as well use that. Still need the number of dimension to get the right path to the field when we call engine
- Store sorting direction as  `A` or `D`. then use enums to get the asc/desc that mui needs + the full word for aria-sort
=> refactor: align sort format and remove hyhpercube dependency

src/table/components/virtualized-table/FullSizeContainer.tsx, src/table/components/virtualized-table/TableContainer.tsx
Fixes an issue where the totals row would be poorly position if a used change to a page with just a few rows
Before:
After:
=> fix: totals bottom position in vt mode

.circleci/config.yml
This should improve the run time and make so that you can see in your PR which jobs are failing
=> ci: use workflows to run jobs in parallel

src/ext/data.js
When deleting alternative columns functions remove in sn-table/ext/data.js is called for both columns and alternative columns. This trigger a re-rendering. For removing alternative columns re-rendering is not necessary.
=> fix: avoid rerendering when deleting alternative columns

src/__test__/test-with-providers.tsx, src/index.ts, src/table/Root.tsx, src/table/components/TableWrapper.tsx, src/table/components/__tests__/TableWrapper.spec.tsx, src/table/components/body/TableBodyWrapper.tsx, src/table/components/body/TableTotals.tsx, src/table/components/body/__tests__/TableBodyWrapper.spec.tsx, src/table/components/body/__tests__/TableTotals.spec.tsx, src/table/components/footer/FooterWrapper.tsx, src/table/components/footer/PaginationContent.tsx, src/table/components/footer/__tests__/PaginationContent.spec.tsx, src/table/components/head/HeadCellMenu.tsx, src/table/components/head/ListBoxWrapper.tsx, src/table/components/head/TableHeadWrapper.tsx, src/table/components/head/__tests__/HeadCellMenu.spec.tsx, src/table/components/head/__tests__/TableHeadWrapper.spec.tsx, src/table/components/virtualized-table/Wrapper.tsx, src/table/components/virtualized-table/types/index.ts, src/table/context/TableContext.tsx, src/table/types.ts
- use `baseProps` for pagination table, instead of props drilling
- add `rootElement` since it is very commonly used
- add `embed` since it is passed all the way to `listBoxWrapper` and that is the only place it is used
I think we can add more stuff. Anything that triggers a rerender all the way from index, would not create extra renders if they are put on the context
=> refactor: use baseProps on context for pagination implementation

src/table/components/head/HeadCellMenu.tsx, src/table/components/head/TableHeadWrapper.tsx, src/table/components/head/__tests__/HeadCellMenu.spec.tsx, src/table/types.ts
Now only showing the search option, thus there is no menu for measures currently. There will be as soon as we add options that exist for both measures and dimensions
=> fix: remove sort options for head menu

src/table/components/virtualized-table/Body.tsx, src/table/components/virtualized-table/Table.tsx, src/table/components/virtualized-table/hooks/__tests__/use-data.test.ts, src/table/components/virtualized-table/hooks/use-data/index.ts, src/table/components/virtualized-table/utils/to-rect.ts
This PR reduces the occurrence of flickering when data becomes stale, ex. new layout triggered by selections in some other object, property changes or changing page.
**`Body` component re-render flow:**
BEFORE:
1. Reset data state to an empty array
2. Render Body with the empty array as data (this would cause the flickering)
3. Call engine to fetch new data
4. Set state with new data
5. Render Body with new data
AFTER:
1. Render Body with previous data (use the deferred row count to guard against row count changes that does not match the length of the previous data)
2. Call engine to fetch new data
3. Set state with new data
4. Render Body with new data
There as still an issue with the scroll position being reset on step 1, which under certain circumstances can be seen as a kind of …
=> fix: reduce flickering with stale data

src/ext/property-panel/settings.js
By design we only want to show visibility option if chart exploration is toggled on
=> fix: show chart exploration visibility option only if its enabled

src/ext/index.js
As request we need to disable the select all option for chart exploration column handler component
=> fix: disable select all for chart exploration column handler

src/__test__/handle-data.spec.ts, src/handle-data.ts, src/table/context/TableContext.tsx, src/table/hooks/__tests__/use-column-widths.spec.ts, src/table/hooks/use-column-widths.ts, src/types.ts
using the head and body styling to calculate/estimate the width of header, totals and body. 
Currently ignoring the extra padding differences between header and body. My next step is to fix the header label button for text wrap and font size. Then it makes sense to get an optimized result for hug.
=> fix: calculate hug based on real font style

src/table/virtualized-table/Table.tsx, src/table/virtualized-table/hooks/__tests__/use-scrollbar-width.spec.ts, src/table/virtualized-table/hooks/use-data/index.ts, src/table/virtualized-table/hooks/use-get-hypercube-data-queue.ts, src/table/virtualized-table/hooks/use-scroll-handler.ts, src/table/virtualized-table/hooks/use-scrollbar-width.ts, src/table/virtualized-table/utils/to-rect.ts
As the width and height is computed by the table, when the browsers add a scrollbar, some of the space included in the width/height is occupyed by the scrollbar. This can cause the effect that a vertical scrollbar can trigger a horizontal scrollbar to appear, and vice-versa.
I had hoped I would be able to find a better solution but none so far. So in this PR there is an attempt to discover if there is a scrollbar, if so, measure its width and reduce that from the width/height of the table and re-render it.
=> fix: scrollbar width vt mode

src/table/virtualized-table/Body.tsx, src/table/virtualized-table/hooks/use-dynamic-row-height.ts, src/table/virtualized-table/utils/get-height.ts
When the table was resized in virtual scroll mode, rows would appear to be flickering a lot. That was due to `Math.round` was used in some places but not others. So when computed row height, it would jump between a rounded value and a decimal value.
=> fix: flickering on resize

src/table/virtualized-table/TotalsCell.tsx
Farily sure we had bold font weight for totals row. This PR enables that again as it appears to have disappeared.
=> fix: totals font weight

jest.setup.js, src/table/hooks/__tests__/use-column-widths.spec.ts, src/table/virtualized-table/__tests__/Table.spec.tsx, src/table/virtualized-table/hooks/__tests__/use-measure-text.test.ts, src/table/virtualized-table/hooks/use-measure-text.ts
All test will now use a global measureText mock.
Had to put in int a `beforeEach` callback as some test calls `jest.restoreAllMock()` which would reset it for all subsequent tests.
=> test: use global measureText mock

playwright.config.ts, test/rendering/utils/run-rendering-tests.ts
Each test suit must run on unique ports to not conflicts with each other
=> test: run rendering tests in parallel

src/table/hooks/__tests__/use-field-selection.spec.tsx
fixed act error for `useFieldSelection`
root cause was this error here:https://github.com/qlik-oss/sn-table/blob/7734f4b60b38f2f675eafbd91c39d187cbe99140/src/table/hooks/use-field-selection.ts#L32-L35
because it was setting state after `app.getField(...)` being resolved!
=> test: fix act error for `useFieldSelection`

src/__test__/test-with-providers.tsx, src/table/virtualized-table/hooks/__tests__/use-scrollbar-width.spec.tsx, src/table/virtualized-table/hooks/use-scrollbar-width.ts
The old logic could end up in what appeared to be a race-condition when it measured the element to determine if there was a scrollbar. I found it occur sometimes when doing selections with the selection toolbar that reduced or increased the number of rows.
=> fix: detect scrollbar size logic

src/table/virtualized-table/__tests__/Table.spec.tsx
The `useFieldSelection` hook used the the `HeadCellMenu` trigger a state update on every first render. I simply remove that by removing a method on `app` that was a requirement for it to happen. It has no actual effect on the tests as it is not interacting with the HeadCellMenu.
=> test: fix act warning in table comp

src/table/virtualized-table/hooks/use-dynamic-row-height.ts
A cell that contained only white space could line break into multiple lines in the virtual scroll table. This not how the pagination table does it, it just ignores all white space. So this fix replicates that.
=> fix: remove white space before measuring cell

src/table/components/head/HeadCellMenu.tsx, src/table/components/head/MenuList/MenuGroup.tsx, src/table/components/head/MenuList/RecursiveMenuList.tsx, src/table/components/head/MenuList/__tests__/MenuGroup.spec.tsx, src/table/types.ts, src/table/utils/handle-key-press.ts
- should focus on the first option in the menu when opening
- should open the cascading menu when activating the button
- should focus the ... button again when closing the menu
- either by esc or by choosing an option
https://user-images.githubusercontent.com/4471489/222143020-5f44758b-ae38-4659-a2e1-e32a831699c6.mov
=> feat(a11y): make keyboard navigation work for head cell menu

src/ext/property-panel/data.js
Other developers said I should use the definition this way.
=> fix: change definition

src/ext/property-panel/data.js
The default props of a dimension or measure were populated in sense-client by a function `getCreatePropertyHandler` in `default-extension.js`. It expects the definition to be in certain structure so the structure we have for chart exploration was not compatible. This PR fix the problem.
=> fix: default props was not populated properly

src/table/hooks/use-column-widths.ts
Fixes an issue where column widths would not be re-calculated when needed.
The issue could be reproduce like this:
1.  Create a table with a single dimension (1 dim because you don't need more)
2. Set the dimensions `resize type` to `hug`
3. Change the theme in your current context (ex. Qlik Sense) to a theme with a large font-size for the body.
Result:
The column widths would not adjust to the new font-size from the theme.
=> fix: column widths effect dependencies

src/table/pagination-table/components/head/TableHeadWrapper.tsx
Fixes an issue in the pagination table where the totals row would be incorrectly positioned (see screenshot below). This could happen when the table was re-sized. Ex. via object re-size in Qlik Sense or browser window re-sizing.
It did not happen every time. You had to find a scenario where the height of the header row would grow smaller as the table was re-sized.
**Before:**
**After:**
=> fix: white space before totals

src/table/context/TableContext.tsx, src/table/hooks/__tests__/use-column-widths.spec.ts, src/table/hooks/use-column-widths.ts, src/table/virtualized-table/hooks/use-measure-text.ts
Fixes some issue with the hug calculation for column widths:
- Take header button and sort icon into account when measuring header label width
- Take padding into account when measuring totals label width
- Do not measure totals label if totals is not shown
- Adjust the estimated width based on glypth count
Comparison with the native table in Qlik Sense. Both native table and sn-table have "hug" as column width.
=> fix: column width huc calculation

src/ext/property-panel/settings.js
translation is used for the "Styling -->" button in property panel, subtitle is the subtitle in the styling panel header, under the chart name
=> fix: styling label missing

src/table/components/head/ColumnAdjuster.tsx, src/table/types.ts, src/table/virtualized-table/Body.tsx, src/table/virtualized-table/Header.tsx, src/table/virtualized-table/HeaderCell.tsx, src/table/virtualized-table/Table.tsx, src/table/virtualized-table/hooks/__tests__/use-dynamic-row-height.spec.tsx, src/table/virtualized-table/hooks/__tests__/use-scroll-hander.test.ts, src/table/virtualized-table/hooks/use-data/index.ts, src/table/virtualized-table/hooks/use-dynamic-row-height.ts, src/table/virtualized-table/types/index.ts
Fixes an issue where the virtual scroll table would always scroll to the top when the table was resize. For example in Qlik Sense, changing the size of the table by re-sizing it on the grid or enter full screen mode.
Resizing a column still scrolls to the top to avoid issues with cells heights not being properly updated and rather "jumpy" experience during resize.
=> fix: scroll to top on resize

src/table/components/head/ColumnAdjuster.tsx
in the virtual scroll table, adjusting column size by keyboard also scrolls the table
https://user-images.githubusercontent.com/4471489/225260914-2d76cc6c-d79f-4923-8495-42edec213fba.mov
=> fix: adjusting column size by keyboard also scrolls the table

src/ext/property-panel/data.js
Dimension number formatting is using measure number formatting that only works for measure, we need to make a new number formatting for dimensions that work but in the meanwhile we can remove this one.
Before: 
Now:
Heres a video that shows that number formatting works on measures but not on dimensions.
https://user-images.githubusercontent.com/8957233/226564951-3bf7ab9b-50aa-4ce5-84ed-3a944bf7bd0e.mov
=> fix: dimensions no longer have measure number formatting

src/table/virtualized-table/Table.tsx
Reset scroll position on theme change. This is how the old native table in Qlik Sense acts on theme change. It will also make the fix for wrong cell heights on theme changes easier.
=> fix: reset scroll position on theme change

src/__test__/test-with-providers.tsx, src/table/Root.tsx, src/table/components/footer/PaginationContent.tsx, src/table/components/footer/__tests__/PaginationContent.spec.tsx, src/table/context/TableContext.tsx, src/table/pagination-table/components/TableWrapper.tsx, src/table/pagination-table/components/__tests__/TableWrapper.spec.tsx, src/table/types.ts, src/table/virtualized-table/Wrapper.tsx, src/table/virtualized-table/__tests__/Table.spec.tsx, src/table/virtualized-table/__tests__/Wrapper.spec.tsx, src/table/virtualized-table/types/index.ts
Moves the rect to the TableContext. It's required for fixing another issue, otherwise the VT table will run in to issue with the `columnWidths` and `rect` being out-of-sync.
=> refactor: move rect to table context

src/__test__/handle-data.spec.ts, src/handle-data.ts, src/table/components/head/HeadCellContent.tsx, src/table/components/head/HeadCellMenu.tsx, src/table/components/head/__tests__/HeadCellContent.spec.tsx, src/table/hooks/use-selection-reducer.ts, src/table/pagination-table/components/body/TableTotals.tsx, src/table/pagination-table/components/head/TableHeadWrapper.tsx, src/table/utils/__tests__/get-head-icons.spec.tsx, src/table/utils/get-head-icons.tsx, src/table/utils/styling-utils.ts, src/table/virtualized-table/HeaderCell.tsx, src/table/virtualized-table/TotalsCell.tsx, src/table/virtualized-table/hooks/use-data/utils/index.ts, src/types.ts
We have added things to getColumnInfo incrementally and it has become pretty unstructured and complex. There was some weird casting going on etc. This is mostly to prepare for a bug fix, I just broke this part out.
- renaming align props to more similar names
- moving all alignment logic to functions inside handle-data
- do all dimension specific props in on if in getColumnInfo
=> refactor: structuring `getColumnInfo` and text alignment logic

src/nebula-hooks/__tests__/use-sorting.spec.ts, src/nebula-hooks/use-sorting.ts
Since we remove the ability to pass a specific sort direction (ascending/descending) we can remove some logic and corresponding tests.
=> refactor: remove unused code for sorting

src/nebula-hooks/use-pagination-table.ts
when `areBasicFeaturesEnabled === false && usePagination === true` nothing was rendered. We should default to the pagination table in that case
=> fix: show pagination table when flag is off

src/table/components/head/styles.ts
Fixes an issue where the header cell width would be calculated the same, but rendered different when interactions was disable or enabled.
Before:
Sort icon did not occupy any space. For example in Qlik Sense, going from Edit to View mode, could render different line breaks in a header label when a field had "column width" set to "Pixels".
After:
Sort icon occupies space. No difference between the line breaks any more.
=> fix: consistent header cell width

src/table/virtualized-table/hooks/use-dynamic-row-height.ts, src/table/virtualized-table/utils/cell-width-utils.ts
Fixes an issue in virtual scroll table where the cell height for a measure header, would not be properly calculated. Primerly it did not include the width of the "menu button", as that is now also available on the measure label.
=> fix: head cell width

src/nebula-hooks/use-pagination-table.ts, src/nebula-hooks/use-virtualized-table.ts, src/nebula-hooks/virtualized-table/use-wait-for-fonts.ts
Fixes an issue where the width of some text, was measured before all fonts had been loaded.
This could result in that the length of the text in the browser, when it had been rendered, did not match the measured values. Producing artifacts where, for example, text would look like it required 2 lines but was only rendered on a single line.
~~I've only added this check for the virtual scroll table as I've yet to seen any issue with the pagination table.~~
Edit: it actually runs for pagination table too.
Edit2: Added the check for pagination table as it also depends on measuring text using a canvas context.
=> fix: wait for fonts to load

src/table/virtualized-table/hooks/use-heights.ts
Fixes an issue where the totals row was not fully visible when docked at the bottom.
Before:
After:
=> fix: totals row height when docked at bottom

src/table/utils/__tests__/handle-keyboard.spec.ts, src/table/utils/handle-keyboard.ts
pressing space on totals row || any cell of it causes and unnecessary scroll down. This small pr fixes it!
=> fix: pressing space scrolls down on totals row

src/handle-data.ts
when totals label is undefined in layout => VT crashes => this PR is the fix from root cause of it where we safely return an empty string instead in order to prevent crash
=> fix: empty totals label in VT mode

src/index.ts, src/nebula-hooks/use-pagination-table.ts, src/nebula-hooks/use-virtualized-table.ts, src/nebula-hooks/use-wait-for-fonts.ts
The `useWaitForFonts` hook was not working as intended when both tables had it's own usage of it. You could end up in  scenario where toggling the `usePagination` "switch" did not re-render with a different table.
Now both use the same output from the hook, which I think makes more sense anyway as we don't neeed to make duplicate async `load` calls.
=> fix: wait for fonts

src/table/components/CellText.tsx
In the pagination table. Empty cells or cells with only white-space does not render with correct height.
Before:
After:
=> fix: empty cell height

.eslintrc.json, package.json, src/ext/conversion/exportProperties.ts, src/ext/conversion/importProperties.ts, src/ext/conversion/index.ts, src/ext/index.js, src/qlik-object-conversion.d.ts, src/types.ts, yarn.lock
chart conversion task 1:
- enable conditional show for chart conversion by `conversion.conditionalShow.unquarantine(propertyTree.qProperty);`	
-	when a column is hidden in an old table, after converting that old table to the new one, that column remains hidden and vice versa.
chart conversion task 2: column width will be in the next PR
=> feat: restores all qCalcCondition for chart conversion

src/table/components/head/ColumnAdjuster.tsx, src/table/components/head/styles.ts
Found two small issues with the column adjust when using the keyboard.
- lost focus after pressing arrow once, need to stop propagation
- focus was set to chart, not ... menu. Same there, needed to stop propagation
Also, learned a bit about focus-visible a while ago, so we can use that pseudo-class instead of manually blurring when using the mouse.
=> fix: adjuster keyboard issues

src/table/hooks/__tests__/use-column-widths.spec.ts, src/table/hooks/use-column-widths.ts, src/table/pagination-table/components/head/TableHeadWrapper.tsx
When rect.width becomes 0, we early returned and set `columnWIdths` to `[]`. That means some calculations for the VT broke. There is no real reason to early return. The result will be that all columns get the min size.
=> fix: remove sanity check for rect.width === 0

src/table/virtualized-table/Body.tsx
Fixes an issue where the header and body could become out of sync if the scrollbar occupied space in the container element.
Before:
After:
=> fix: header and body out of sync

.gitignore, src/ext/conversion/__test__/export-properties.spec.ts, src/ext/conversion/__test__/import-properties.spec.ts, src/ext/conversion/export-properties.ts, src/ext/conversion/import-properties.ts
Quarantine and unquarantine column order of sn-table so that the property can be stored and recovered correctly.
=> fix: quaratine and unquarantine column order

src/table/Root.tsx, src/table/types.ts
a good example of when to use undefined instead of optional in types
=> fix(pagination-table): miss direction in table wrapper

src/ext/property-panel/settings.js
straight table that has chart exploration enabled and is placed inside a container should not show Chart exploration in the property panel
=> fix: chart exploration should not be in the property panel when straight table is inside container

src/table/virtualized-table/hooks/__tests__/use-data.test.ts, src/table/virtualized-table/hooks/use-get-hypercube-data-queue.ts, src/table/virtualized-table/utils/__tests__/merge-pages.spec.ts, src/table/virtualized-table/utils/merge-pages.ts
This PR changes two things:
1. qDataPage fetches are throttled by 75 ms, instead of "as fast as possible".
2. Pages in are merged so that the GetHyperDataCalls to Engine contains less "pages" with qWidth and qHeight === 1
The intention is to reduce the burden on Engine and in that way also improve the performance. Some smaller tables with a simple data structure are likely getting a small performances hit because of the throttles fetches.
=> perf: throttle page fetch

src/locale/locales/en.json, src/table/components/head/HeadCellMenu.tsx
The button in the header (see image) needs to be label to be accessible. Simply done with a aria-label, since there is no label on the button
=> fix: add aria-label for head menu button

src/table/hooks/use-snapshot.ts, src/table/hooks/use-view-service.ts, src/table/pagination-table/components/TableWrapper.tsx, src/table/pagination-table/components/head/TableHeadWrapper.tsx, src/table/utils/__tests__/find-visible-rows.spec.ts, src/table/utils/find-visible-rows.ts, src/types.ts
**The issue:**
The current sn-table snapshot calculations are not accurate. If the table row is half-visible, it will take it as a totally visible row and if the row is less than 50% visible, it will not consider it as part of the snapshot.
**Solution for pagination mode**
The improvement calculates the exact top row visible height (if there is any) and adjusts the final table scrollTop based on the new calculations to reach to the exact visible row height. The result is a snapshot that fulfills `what you get is what you see`
=> feat: show a snapshot with the exact scroll position

src/table/hooks/__tests__/get-view-state.spec.ts
Due to the unexpected focused test (mistakenly left perhaps) `sn-table` code change are not committable. Throws a linting issue. Hence this was removed.
=> fix: Unexpected focused test

src/nebula-hooks/use-virtualized-table.ts
https://github.com/qlik-oss/sn-table/pull/1055 does not really use virtualized table to render snapshot/pdf. This PR is to restore when a virtualized table should be rendered.
=> fix: do not use virtualized table to render snapshot/pdf

src/table/virtualized-table/hooks/use-dynamic-row-height.ts
The failure to render a cells has to do with the max element dom size being exceeded. This PR just lowers the max allowed size. Where the consequence of that, is that instead of rendering some rows with 3 lines of text, it may now render them with only 1 or 2 lines.
There is a need to take an in-depth look at this and fix the issue in a far more dynamic way. But that is a much much larger and risky change. So this PR takes the easy path that may not work for every browser and machine combination.
=> fix: big table dont render properly

package.json, src/ext/property-panel/data.js
when clicking on percentage column size type, table breaks in sence-client, we noticed that the way we access the enum value is incorrect so this pr fixes it.
also while testing it through sence-client, noticed that the `start:mfe` script in pkg.json was not presented, so feel free to complain about it and tell me to remove it if you think it's not needed
Before fix:
https://github.com/qlik-oss/sn-table/assets/29652890/aaa7166f-bee3-4211-b2f6-75e1f3fbe279
After Fix: 
https://github.com/qlik-oss/sn-table/assets/29652890/f458adfe-6f06-441a-9500-f983d0e13634
=> fix: use capital Percentage while accessing enum value

src/table/pagination-table/components/body/TableBodyWrapper.tsx
when keyboard navigation is off, AND there is no totals row, the first body cell picks up tab a tab index of 0, which results in below scenario: 
So this PR fixes that base on the rule for tab stops with new head cell (we might have only 1 tab stop in table), So if the flag is on -> we should directly return -1 for first body cell, where we decide to let it have tab stop or not.
the result becomes:
https://github.com/qlik-oss/sn-table/assets/29652890/5bcfccf0-8446-4c92-b7ca-26b0b82635a8
=> chore: fix tab stop when keyboard navigation is off
